server:
  port: 9002
spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848 #nacos注册中心

#暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
