server:
  port: 9001
spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      server-addr: localhost:8848 #Nacos配置地址

#暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
