server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848
    gateway:
      routes:
        - id: consumer_router
          uri: lb://cloud-consumer # 三种方式
          predicates:
            - Path=/consumer/** # 断言，路径匹配的进行路由，追加在目标uri后面

#第一种：ws(websocket)方式: uri: ws://localhost:9000
#第二种：http方式: uri: http://localhost:8130/
#第三种：lb(注册中心中服务名字)方式: uri: lb://brilliance-consumer
