server:
  port: 80
spring:
  application:
    name: cloud-cousumer
  cloud:
    nacos:
      server-addr: localhost:8848 #Nacos注册中心地址


#暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: "*"

#消费者将要去访问的服务名称(注册进nacos的微服务提供者)
server-url:
  nacos-user-service: http://cloud-provider
